env:
  global:
  - GH_REF: github.com/nhz-io/nhz-throttle.git
  - secure: aXKHHJmD6WJaWeEEh7On0Nn7/dma7vkE6JPUlF8U2hMfgmqhw7uMXTDEDF72fSvvv12gw7F55KBfjDAaqNeYzaQIvBBVV9uag2Pd87iNjFYwRTp4/QtDbCqTveHm53UBg8/18NoSOf/YaeL78kKK6n2gEWenGnBVKu3ekuUcNd2rqFS0zMQSF9MH+ApwxC6g0+Kl7nGF8GEGCNTm7g7j0IM3TX8NfjxV6McWpagOcUinKF0LS9SB9QS/u5BI01yMCYa3vitjzBt8snmdxetdnK1Ezw2g4Ps0cMRPkm7kVBVQXKUvm99ex93Zkt5/cCeMn7SGxMnzUW3bFgK+RrOcdmK6maR2Ao9KPKMoysC+u3yiGrHhmZedJnyROconIi5Rnpa7nC9EFYe+R4EOjO/9mmgo98tiSn6r61/ID6LrzgFexamIY19QGJZoEcc+QR3Hy9Y2wjw6R59VAgVx1Z8GwZY3EiO4kX/WBz8r/OnABY3/HAzybFagcGOjfEwtVJMqRv1vo8b/KL8bALr32ESqOs/iletfel9/o+pagItABW5d5VZ+RaE5nSQOy5J0I3/+jEcFxLlESK0DdKaiHiKgKynq1gMAnmkF3utd4tI8cTBSUhme58Xp2Cpeg0nSeMc36Ji4gp9jP+55EQtjxlg+eqfqAaeoxg0r6NKe6Jt6lPI=
language: node_js
node_js:
- '0.11'
- '0.12'
- iojs
- '4.2'
- '5.1'
script: npm run-script dist
deploy:
  provider: npm
  email: dev@nhz.io
  skip_cleanup: true
  api_key:
    secure: egyswKI14SYqpX85VLp/WKE7byasMo/lxopOd/2aYO/d4tifeUuWkqwJ9tbX2Cehg5yrEBik4FatX+VKV5QyEPmp4+7fQlHBaRuMDYzuHZxZi15QYbRix2Av1QFhow5srze9qhoIxC4oFMAJFq2w96HE4IfaLT89OqnH/GDhC8tA0C9Z0bLRjsszCF+ZIDI+3mS6cbx9LycK15zqU33t8N39uPIl/4MNqIi5ms24UIIpFDdoY53YZFz/p4bsD57ylmSAIIZrGSTpcSvwrh7PQgAm23rFdySxNhJ0VCvST45pNgVqFC1a1wRX16rHZ9tiS88FwUBt7NxMnVUp5TVqxI0Z+UOPHF/2MZhqZWjxs3RKQw3sCfQobD3e230vNxZstqmZP9ZKKEwyj1ODxPaPOQIgm4Yuf5ImvguEvxmorSGcQgURBPw9Geeit8Egrwz94T0FM+lGndFuG2fDzsh8obFVWuZ8zlwL6mS9NrZRZGWo1r2ZLxX8BFUAe418BCrEN8nLkelA18LFcOheUqYyXJ7B6j0KcF721ekkNDwbW4sE+caBubsEQKREuQC7F5zDKpGaanLO5atD6ET/XABqj+pZ+3gbGGDzVN8qK7s6HI7m/NIMvNOTeiGHR00GbD7IOK5cmbHmI9xg3U2oMXJi2xwZjYnxAHzVQY7b8J1LUcQ=
  on:
    repo: nhz-io/nhz-throttle
    branch: master
after_deploy:
- bash ./dev/gh-pages.sh
