env:
  global:
  - GH_REF: github.com/nhz-io/nhz-throttle.git
  - secure: XR81l64AJZWvIduhGNh7JZipQeRIRqG5bIAu38nmrf0bQJAK70STtVQUMBcpMEKlRL2r06QYAzVD3OKtiq5TnLTHoMfCW+XhX5+KvZI+zs3P8gjGBkopHQWg0H9e29HjsryXCvK3/8//A2q5Akl2roGDXqiF/63cn4yqiF3fT6Liigxra/0pRmeEH6EUVVXaSJ9YkQ0CbDB0aw2k9boQALpwW3SrXUUavoY1LmZ58czc5dLiGXuN3kxplELVk2x/A+ZfjevGsRdHjR56+N/Pgs5+zfm/YBPqRQxDosVbtaO3n3AaAvL3sphJ5hmUN3ffWeWQBubNKSDdxataBm3Hg3TJvW/JttypzQhYMW7n1bkYaVuzAvsS2kapaE/5PTSAlmAPyC4f/egWskDpi1seDAlJ7KKmirxUglnw0xVCfmCLGIwCmIm8Z0crNXzap0Kxf8iv33zHFGgF/Kqf6C7Urheut1M0bsKNZFhmGoFt8nHaRRXDOPg60ZYRMfE2H7M8OZYdfCOsedvHUeh0Jl3fsivnmdt9S8n03gZ7QmTejoQht3+wGo+F6ZYN7KnIq/YXn6uRSY5TkVCyi2v2K7vc3MmTe0FGGqybEgEUB0gMuC5jrG0jC255t8C8ru9MTAB8RwJQQum/MfvN16WIusvODDK4njiZ8ipjBSGQ3r9zu6g=
language: node_js
node_js:
- '0.11'
- '0.12'
- iojs
- '4.2'
- '5.1'
matrix:
fast_finish: true
script: npm run-script dist
deploy:
  provider: npm
  email: dev@nhz.io
  skip_cleanup: true
  api_key:
    secure: egyswKI14SYqpX85VLp/WKE7byasMo/lxopOd/2aYO/d4tifeUuWkqwJ9tbX2Cehg5yrEBik4FatX+VKV5QyEPmp4+7fQlHBaRuMDYzuHZxZi15QYbRix2Av1QFhow5srze9qhoIxC4oFMAJFq2w96HE4IfaLT89OqnH/GDhC8tA0C9Z0bLRjsszCF+ZIDI+3mS6cbx9LycK15zqU33t8N39uPIl/4MNqIi5ms24UIIpFDdoY53YZFz/p4bsD57ylmSAIIZrGSTpcSvwrh7PQgAm23rFdySxNhJ0VCvST45pNgVqFC1a1wRX16rHZ9tiS88FwUBt7NxMnVUp5TVqxI0Z+UOPHF/2MZhqZWjxs3RKQw3sCfQobD3e230vNxZstqmZP9ZKKEwyj1ODxPaPOQIgm4Yuf5ImvguEvxmorSGcQgURBPw9Geeit8Egrwz94T0FM+lGndFuG2fDzsh8obFVWuZ8zlwL6mS9NrZRZGWo1r2ZLxX8BFUAe418BCrEN8nLkelA18LFcOheUqYyXJ7B6j0KcF721ekkNDwbW4sE+caBubsEQKREuQC7F5zDKpGaanLO5atD6ET/XABqj+pZ+3gbGGDzVN8qK7s6HI7m/NIMvNOTeiGHR00GbD7IOK5cmbHmI9xg3U2oMXJi2xwZjYnxAHzVQY7b8J1LUcQ=
  on:
    repo: nhz-io/nhz-throttle
    branch: master
after_deploy:
  - bash ./dev/gh-pages.sh
